import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Squirtle from '@/components/lottie'
import Navbar from '@/components/navbar'
import React from "react";
import Lottie from "lottie-react";
import waterAnimation from "../public/water.json";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mainCont'>
      <Navbar />
        <div className='pokeCont'> <Squirtle /></div>
        <div className='textCont'>
        <h1>Ivan Tong</h1>
        <h2>Product Designer</h2>
        <h2>Digital Designer</h2>
        <h2>UI/UX Designer</h2>
        <h2>Graphic Designer</h2>
        </div>
        <div className='water'><Lottie animationData={waterAnimation} loop={true} />;</div>
      </main>
    </>
  )
}
